matrix:
  stages:
  - lint
  - test
  x-backend:
    language: python
    python: &1
    - '3.8'
    before_install: cd backend
    install: &2
    - pip install pipenv
    - pipenv install --dev --deploy
  x-frontend:
    language: node_js
    node_js: &3
    - node
    before_install: cd frontend
  include:
  - stage: lint
    language: python
    python: *1
    before_install: cd backend
    install: *2
    script:
    - black . --check
    - pylint src tests/*
    - flake8
    - bandit . -r -c .bandit
  - stage: test
    language: python
    python: *1
    before_install: cd backend
    install: *2
    script:
    - pytest
  - stage: lint
    language: node_js
    node_js: *3
    before_install: cd frontend
    script:
    - npm run eslint-check
    - npx prettier -c src/**/*.js src/*.js
    - npm run lint
  - stage: test
    language: node_js
    node_js: *3
    before_install: cd frontend
    script:
    - npm test
deploy:
  provider: heroku
  api_key:
    secure: yMxaIJmNOJgbqGnW1iUHrVNy/qPgIEFEvNkr17p/59Pz/QjJ2t4V8vB4hFIEnGI8t06tZxD/Guj8lp4mLiGk2LlMgBwJlKdEfG9lJMJqWq1hOsQFL2oEok31ToIKFilvWgwIIlsmPlECOj/kS99qOvD7xKr9hTfcwn0Z/GV2BclaeFpOXk6pxIbNkvKS2FBf/RZx0K8b8Q9/bHKo0s39BNOoU92xo6UesTqQ2SC+qAsM4HVFj4Ci2lKPNKSTtw8FTPqNNP/cVs+/Xm3QI5pjAeeLF6RVb+Y25DmkOWMek6ZgI2BfAqfeY2i/a06+gske/1o3EACtxUrTFKQq+Pf71dVmr4EgKd2PrFOZnMPAqnGlATlNTXQfJO01/OhRQ+PCHGbBMRl8QdRlvmnGLn+kGWL+TRAjhvURYO/W4t7lXlpCy71yTxBqNVatxprNWsEGpJR3Ais5PCe2brU2sltSKzhMESa7tVZtCfKVXuiANA04TE1jT+3orsMY3r+Ljn3kclKpxHZNYsWDZaOJp28PvXAFqSHss2snM5bWV1YoLHBKcgmyax503xTFkPkrPzs0LfvIfkjWbf2csBDCgRCke4fF7BYjU08q0VeQEFxvOHpQvQpvkSaMo9K8VWrJt8Q1wrsrNf0rTOnCCsGi/C705toaOhyjTok5PFalJl9Zob4=
  app: sudoku-battle-royale
  on:
    repo: nokia-wroclaw/innovativeproject-sudoku
    branch: devops/auto_deployment
